-- AlterTable
ALTER TABLE `produtos` MODIFY `tipo` ENUM('MONITOR', 'TECLADO', 'MOUSE', 'HEADSET', 'CADEIRA', 'MESA', 'GABINETE', 'PLACA_DE_VIDEO', 'PLACA_MAE', 'PROCESSADOR', 'MEMORIA_RAM', 'HD', 'SSD', 'FONTE', 'COOLER', 'WEBCAM', 'MICROFONE', 'CAIXA_DE_SOM', 'OUTRO') NOT NULL DEFAULT 'OUTRO';
